# Generated by Django 2.2.3 on 2019-09-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontent',
            name='title',
        ),
        migrations.AddField(
            model_name='blogcontent',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bloggroup',
            name='href',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blogitem',
            name='href',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blogitem',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='bloggroup',
            name='kind',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='kind',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='blogitem',
            name='title',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
